# lsystem.py
# Di Luo
# CS 151 Fall 2018
# Project 8: Better Trees
# Version 2

import sys

# a class
class Lsystem:
    def __init__(self, filename = None):
        ''' Initialize an empty L-system and import base and rule of a L-system from a file if exists '''
        self.base = ''
        self.rules = []
        if filename != None:
            self.read(filename)
    
    def setBase(self, newbase):
        '''Set self.base with a new base'''
        self.base = newbase

    def getBase(self):
        '''Get method for base'''
        return self.base

    def getRule(self, index):
        '''Get method for rule in self.rules'''
        return self.rules[index]
    
    def addRule(self, newrule):
        '''Add new rule to self.rules'''
        self.rules.append(newrule)

    def numRules(self):
        '''Count the number of rules in self.rules'''
        return len(self.rules)

    def read( self, filename ):
        '''Open the file, read in the Lsystem information, reset the base and rules fields of self, 
        and then store the information from the file in the appropriate fields'''
        fp = open(filename, 'r')
        for line in fp:
            words = line.split()
            if words[0] == 'base':
                self.setBase(words[1])
            elif words[0] == 'rule':
                self.addRule([words[1], words[2]])
        fp.close()

    def replace(self, istring):
        '''Scan through the string, and for each character test if there is a rule. 
        If a rule exists, add the replacement to a new string, 
        If no rule matches, add the character itself to the new string'''
        tstring = ''
        for c in istring:
            found = False
            for rule in self.rules:
                if c == rule[0]:
                    tstring += rule[1]
                    found = True
                    break
            if not found:
                tstring += c 
        return tstring
    
    def buildString(self, iterations):
        ''' Return a string generated by applying the L-system rules for a number of iterations '''
        nstring = self.base
        for i in range(iterations):
            nstring = self.replace(nstring)
        return nstring
    
    def __str__(self):
        ''' Return formatted string of base and rules of L-system'''
        lsys = 'base ' + self.getBase()
        for i in self.rules:
            lsys += '\nrule ' + i[0] + ' -> ' + i[1]

        return lsys

        
def main(argv):

    if len(argv) < 2:
      print('Usage: lsystem.py <filename>')
      exit()

    filename = argv[1]
    iterations = 2

    lsys = Lsystem()

    lsys.read( filename )
    print(lsys)
    
    return

if __name__ == "__main__":
    main(sys.argv)